# Generated by Django 2.2 on 2020-07-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal_user',
            name='account_type',
            field=models.BooleanField(default=False),
        ),
    ]
