# Generated by Django 2.2 on 2020-07-09 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('company_name', models.CharField(blank=True, max_length=264)),
                ('designation', models.CharField(blank=True, max_length=264)),
                ('address', models.TextField(blank=True, max_length=500)),
                ('telephone_no', models.CharField(blank=True, max_length=264)),
                ('email_id', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=264)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
