# Generated by Django 2.2 on 2020-07-16 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS_Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_to', models.CharField(blank=True, max_length=1000)),
                ('send_message', models.CharField(blank=True, max_length=1000)),
                ('status', models.CharField(blank=True, max_length=1000)),
                ('lead_status', models.CharField(blank=True, max_length=1000)),
                ('send_date_time', models.DateTimeField(auto_now_add=True)),
                ('send_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
