# Generated by Django 2.2 on 2020-07-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms_usage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
