# Generated by Django 2.2 on 2020-07-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_sms', '0002_sms_usage_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sms_usage',
            old_name='send_to',
            new_name='send_to_name',
        ),
        migrations.AddField(
            model_name='sms_usage',
            name='send_to_number',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
